### ISSUE TITLE
verifier issue

### ISSUE THREAD

**Issue by uday1kiran** [Azure-Samples/ms-identity-node#15]
Getting this error

```
C:\test\ms-identity-node\app\auth\AuthProvider.js:132
                codeVerifier: req.session.pkceCodes.verifier,
                                                    ^

TypeError: Cannot read properties of undefined (reading 'verifier')
    at C:\test\ms-identity-node\app\auth\AuthProvider.js:132:53
    at Layer.handle [as handle_request] (C:\test\ms-identity-node\app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\test\ms-identity-node\app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\test\ms-identity-node\app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\test\ms-identity-node\app\node_modules\express\lib\router\layer.js:95:5)
    at C:\test\ms-identity-node\app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\test\ms-identity-node\app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\test\ms-identity-node\app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\test\ms-identity-node\app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\test\ms-identity-node\app\node_modules\express\lib\router\index.js:47:12)
```

**Comment by berk76** [comment]
Hi,
I am experiencing the same problem.

It looks like `cryptoProvider` returns verifier as undefined occasionally
```
const { verifier, challenge } = await this.cryptoProvider.generatePkceCodes();
```

**Comment by saeedalhamed** [comment]
Any suggestions to resolve that? we have a support ticket opened for it, please advise.

**Comment by uclnj** [comment]
I seem to have resolved the verifier issue as I have been using cookie-session with an app.use(...) but this example seems to build the application session using "cookie-parser."  Swapping to cookie-parser and removing my app session cookie use resolved it.

Now to get it working on cookie-session instead.
