### ISSUE TITLE
redirect_uri_empty: A redirect URI is required for all calls, and none has been set.

### ISSUE THREAD

**Issue by ympondaven** [Azure-Samples/ms-identity-node#18]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> don't know how to reproduce but a lot of users have the issue but we've not found any reason. 
They have this error when trey're trying to login after using microsoft authenticator : 
ClientConfigurationError: redirect_uri_empty: A redirect URI is required for all calls, and none has been set.
    at ClientConfigurationError.AuthError [as constructor] (/app/node_modules/@azure/msal-common/dist/index.cjs.js:499:24)
    at ClientConfigurationError.ClientAuthError [as constructor] (/app/node_modules/@azure/msal-common/dist/index.cjs.js:819:28)
    at new ClientConfigurationError (/app/node_modules/@azure/msal-common/dist/index.cjs.js:1560:28)
    at ClientConfigurationError.createRedirectUriEmptyError (/app/node_modules/@azure/msal-common/dist/index.cjs.js:1569:16)
    at RequestValidator.validateRedirectUri (/app/node_modules/@azure/msal-common/dist/index.cjs.js:3582:44)
    at RequestParameterBuilder.addRedirectUri (/app/node_modules/@azure/msal-common/dist/index.cjs.js:3711:26)
    at AuthorizationCodeClient.<anonymous> (/app/node_modules/@azure/msal-common/dist/index.cjs.js:5881:46)
    at step (/app/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
    at Object.next (/app/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
    at /app/node_modules/@azure/msal-common/dist/index.cjs.js:53:71

it's not for all users. I can't reproduce this error. 
some users tried to remove cookies or use an other browser with success. 
I've tried to remove the cookie (connect.sid) on the login and logout page. Does not seam to change anything for our users. 

A redirect exist in the configuration and works fine for a lot users. 

### Any log messages given by the failure

They have this error : 
ClientConfigurationError: redirect_uri_empty: A redirect URI is required for all calls, and none has been set.
    at ClientConfigurationError.AuthError [as constructor] (/app/node_modules/@azure/msal-common/dist/index.cjs.js:499:24)
    at ClientConfigurationError.ClientAuthError [as constructor] (/app/node_modules/@azure/msal-common/dist/index.cjs.js:819:28)
    at new ClientConfigurationError (/app/node_modules/@azure/msal-common/dist/index.cjs.js:1560:28)
    at ClientConfigurationError.createRedirectUriEmptyError (/app/node_modules/@azure/msal-common/dist/index.cjs.js:1569:16)
    at RequestValidator.validateRedirectUri (/app/node_modules/@azure/msal-common/dist/index.cjs.js:3582:44)
    at RequestParameterBuilder.addRedirectUri (/app/node_modules/@azure/msal-common/dist/index.cjs.js:3711:26)
    at AuthorizationCodeClient.<anonymous> (/app/node_modules/@azure/msal-common/dist/index.cjs.js:5881:46)
    at step (/app/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
    at Object.next (/app/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
    at /app/node_modules/@azure/msal-common/dist/index.cjs.js:53:71

### Expected/desired behavior
>
supposed to go on the home page ( / )

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Server : 
 OS Ubuntu 22.04.3 LTS
Nodejs v20.11.0
 "@azure/msal-node": "^1.17.3",

Client: 
same issue using chrome on mac or edge on windows. Not found any common point.
This configuration did not work before to clean all cookies : 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### Versions
>

### Mention any other details that might be useful

any ideas may be helpful ! 
Kind regards,
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by caesarsol** [comment]
any update on this?
